spring:
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_SERVICE:kafka-agg:9092}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      trusted-packages: java.lang
    producer:
      bootstrap-servers: ${KAFKA_SERVICE:kafka-agg:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  sleuth:
    kafka:
      enabled: false
    propagation:
      type: B3
    opentracing.enabled: true
  zipkin:
    enabled: false

server:
  port: ${SERVER_PORT:5002}

logging:
  level:
    root: INFO
    brave: DEBUG
