spring:
  kafka:
    consumer:
      bootstrap-servers: kafka-agg:9092 #when using kubefwd
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      trusted-packages: java.lang
    producer:
      bootstrap-servers: kafka-agg:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      interceptor-classes: me.kzkvv.springsleuthspantest.SpringKafkaTracer

  sleuth:
    kafka:
      enabled: false
    propagation:
      type: B3
    opentracing.enabled: true
  zipkin:
    enabled: false

server:
  port: 5002

logging:
  level:
    root: INFO
    brave: DEBUG
